# This is an example config, please edit it and rename it to "config.toml".
title = "onefolder"

[server]
host_url = "https://oneindex-nodejs.example.org"
root_path = "/path/"

[test]
listen = 3000  #port or unix socket