# This is an example config, please edit it and rename it to "config.toml".
title = "Onefolder" #the name of your website

[server]
listen = 3000  #port or unix socket

[common]
root_path = "/path/" #root path for Onedrive's listing
view = "material" #theme of the web page, now can be "simple", "chromium" or "material"